import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import client from "../apollo-client";
import { gql } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ countries }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Welcome Next Js</h1>
        <div className={styles.grid}>
          {countries.map((country: any) => (
            <div key={country.code} className={styles.card}>
              <h3></h3>
              <p>
                {country.code} - {country.emoji}{" "}
              </p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `,
  });

  return {
    props: {
      countries: data.countries.slice(0, 120),
    },
  };
}
